#!/bin/sh

echo "Waiting for backend Swagger spec..."
until wget -qO /tmp/swagger.json http://backend:5000/swagger/v1/swagger.json; do
  echo "Waiting..."
  sleep 3
done

echo "Swagger spec available. Generating SDK..."
openapi-generator-cli generate \
  -i /tmp/swagger.json \
  -g typescript-axios \
  -o /local/generated-sdk \
  --additional-properties=basePath=window.__env?.API_URL,useObjectParameters=true \
  --type-mappings=set=Array \
  --global-property=skipFormModel=false

# Patch the base.ts file to use environment variable
echo "Patching base.ts to use environment variable..."

# Create a temporary file with the new content
cat > /local/generated-sdk/base.ts.tmp << 'EOL'
/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

// Use the globally declared Window interface from env.d.ts
export const BASE_PATH = (window.__env?.API_URL || "").replace(/\/+$/, "");

export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
}

export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

export const operationServerMap: ServerMap = {};
EOL

# Replace the original file with our new version
mv /local/generated-sdk/base.ts.tmp /local/generated-sdk/base.ts

echo "SDK generation complete!"