/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * API for the BUILD.ING Document Management System including Tika integration
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

