services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=bitandbeam;Username=postgres;Password=postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:5000

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"   # Ollama internal API
      - "8000:8000"    # FastAPI external endpoint

  openapi-client:
    image: openapitools/openapi-generator-cli
    container_name: openapi_generator
    depends_on:
      - backend
    entrypoint: /bin/sh -c "
      apk add curl && \
      until curl -s http://backend:5000/swagger/v1/swagger.json > /tmp/swagger.json; do echo 'Waiting for backend...'; sleep 3; done && \
      openapi-generator-cli generate \
        -i /tmp/swagger.json \
        -g typescript-axios \
        -o /local/generated-sdk"
    volumes:
      - ./frontend/src/api:/local/generated-sdk

  postgres:
    image: postgres:17
    container_name: bitandbeam_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitandbeam

volumes:
  pgdata:
