services:
  backend:
    image: ghcr.io/amosproj/bitandbeam-backend:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=bitandbeam;Username=postgres;Password=postgres
    depends_on:
      - postgres
    ports:
      - "5000:5000" 

  frontend:
    image: ghcr.io/amosproj/bitandbeam-frontend:latest
    restart: always
    environment:
      - API_URL=http://backend:5000
    depends_on:
      - backend
    ports:
      - "8080:80"  # Optional: expose only if needed externally

  postgres:
    image: postgres:17
    container_name: bitandbeam_postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitandbeam

  web:
    image: ghcr.io/amosproj/bitandbeam-web:latest
    restart: always
    ports:
      - "80:80"

volumes:
  pgdata:
