using BitAndBeam.Tika;
using BUILD.ING.Data;
using BUILD.ING.Models;
using BUILD.ING.Services;
using BUILD.ING.Swagger;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.Extensions.FileProviders;
using Microsoft.OpenApi.Models;



var builder = WebApplication.CreateBuilder(args);
var conn = builder.Configuration.GetConnectionString("DefaultConnection");
Console.WriteLine($"⛳ Connection String: {conn ?? "null"}");

var MyAllowSpecificOrigins = "_myAllowSpecificOrigins";

builder.Services.AddCors(options =>
{
    options.AddPolicy(name: MyAllowSpecificOrigins,
        policy =>
        {
            policy.WithOrigins("http://localhost:8080") // <-- Angular dev server
                .AllowAnyHeader()
                .AllowAnyMethod();
        });
});

builder.Services.AddControllers();
// Add services to the container.
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection"))
        .EnableSensitiveDataLogging()
        .LogTo(Console.WriteLine, LogLevel.Information));

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    options.IncludeXmlComments(xmlPath);

    options.SwaggerDoc("v1", new OpenApiInfo { Title = "BUILD.ING API", Version = "v1" });
    options.SchemaFilter<BuildingRequestExampleSchemaFilter>();

    // Add support for file uploads in Swagger UI
    options.OperationFilter<SwaggerFileOperationFilter>();

    // Explicitly define the multipart/form-data content type for file uploads
    options.MapType<IFormFile>(() => new OpenApiSchema
    {
        Type = "string",
        Format = "binary"
    });
}); //load the comments from the .xml doc generated by the compiler

// Add health check services
builder.Services.AddHealthChecks()
    .AddCheck<TikaHealthCheck>("tika_health_check",
        failureStatus: HealthStatus.Degraded, // Don't fail app startup if Tika is down
        tags: new[] { "ready", "tika" }, // Tag for grouping
        timeout: TimeSpan.FromSeconds(5));

builder.Services.AddHttpClient();

// Register Tika service
builder.Services.AddSingleton<TikaService>();
builder.Services.AddSingleton<TikaHealthCheck>();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.Migrate(); //führt Migration beim Start automatisch aus

    // Run health checks during startup to verify Tika connectivity
    var healthCheckService = scope.ServiceProvider.GetRequiredService<HealthCheckService>();
    await healthCheckService.CheckHealthOnStartupAsync(scope.ServiceProvider);

// Configure the HTTP request pipeline.
app.UseStaticFiles();
app.UseSwagger();
app.UseSwaggerUI(c => {
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "BUILD.ING API v1");
    c.RoutePrefix = "swagger";
    c.EnableDeepLinking();
    c.DefaultModelExpandDepth(2);
    c.DefaultModelsExpandDepth(1);
    c.DocExpansion(Swashbuckle.AspNetCore.SwaggerUI.DocExpansion.List);
});
app.UseCors(MyAllowSpecificOrigins);
app.UseHttpsRedirection();
app.MapControllers();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast")
.WithOpenApi();

// Add health check endpoints
app.MapHealthChecks("/healthz"); // Basic health check endpoint that returns HTTP 200

// Detailed health check endpoint for Tika
app.MapHealthChecks("/healthz/tika", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
{
    Predicate = (check) => check.Tags.Contains("tika"),
    ResponseWriter = HealthCheckExtensions.WriteDetailedJsonResponse,
    ResultStatusCodes =
    {
        [HealthStatus.Healthy] = StatusCodes.Status200OK,
        [HealthStatus.Degraded] = StatusCodes.Status200OK, // Still return 200 but with degraded status in body
        [HealthStatus.Unhealthy] = StatusCodes.Status503ServiceUnavailable
    },
    AllowCachingResponses = false
});

// Ready check endpoint that includes Tika
app.MapHealthChecks("/healthz/ready", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
{
    Predicate = (check) => check.Tags.Contains("ready"),
    ResponseWriter = HealthCheckExtensions.WriteDetailedJsonResponse,
    AllowCachingResponses = false
});

// Liveness check endpoint
app.MapHealthChecks("/healthz/live", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
{
    Predicate = _ => false
});

//Just to set a route at /
app.MapGet("/", () => "🚀 API is running! Visit /swagger , /weatherforecast or /healthz.");

// Ensure the documents folder exists
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider("/app/documents"),
    RequestPath = "/documents"
});

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int) (TemperatureC / 0.5556);
}
