name: Backend Linting

on:
  push:
    branches:
      - main
    paths:
      - 'BitAndBeam/backend/BUILD.ING/**'
  pull_request:
    branches:
      - main
    paths:
      - 'BitAndBeam/backend/BUILD.ING/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BitAndBeam/backend/BUILD.ING

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Fix Formatting
        run: |
          dotnet format

      - name: Fail if formatting issues are detected
        run: |
          dotnet format --verify-no-changes --no-restore --severity error || exit 1