name: Start default web service

on:
  push:
    branches:
      - main_cleanup

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Deploy Docker Images
        run: |
          cd BitAndBeam
          
          # Log in to GHCR (if not already done)
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Pull the images using the prod compose file
          docker-compose -f docker-compose-prod.yml pull

          # Recreate containers using the prod compose file
          docker-compose -f docker-compose-prod.yml down
          docker-compose -f docker-compose-prod.yml up -d