name: Start default web service

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set date-based image tag
        id: date
        run: echo "DATE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./BitAndBeam/frontend
          push: true
          tags: |
            ghcr.io/amosproj/bitandbeam-frontend:latest
            ghcr.io/amosproj/bitandbeam-frontend:${{ github.sha }}
            ghcr.io/amosproj/bitandbeam-frontend:main-${{ steps.date.outputs.DATE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./BitAndBeam/backend
          push: true
          tags: |
            ghcr.io/amosproj/bitandbeam-backend:latest
            ghcr.io/amosproj/bitandbeam-backend:${{ github.sha }}
            ghcr.io/amosproj/bitandbeam-backend:main-${{ steps.date.outputs.DATE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: ./BitAndBeam/web
          push: true
          tags: |
            ghcr.io/amosproj/bitandbeam-web:latest
            ghcr.io/amosproj/bitandbeam-web:${{ github.sha }}
            ghcr.io/amosproj/bitandbeam-web:main-${{ steps.date.outputs.DATE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload project to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROJECT_SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "BitAndBeam"
          target: "~/"

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROJECT_SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/BitAndBeam

            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Remove old containers
            docker compose -f docker-compose-prod.yml down

            # Remove only specific old images to force update
            docker rmi ghcr.io/amosproj/bitandbeam-frontend:latest || true
            docker rmi ghcr.io/amosproj/bitandbeam-backend:latest || true
            docker rmi ghcr.io/amosproj/bitandbeam-web:latest || true

            # Re-pull latest versions
            docker compose -f docker-compose-prod.yml pull --no-cache

            # Start fresh with latest images
            docker compose -f docker-compose-prod.yml up -d --force-recreate

            # Optional: clean up unused resources
            docker system prune -af


