name: Frontend Linting

on:
  push:
    paths:
      - 'BitAndBeam/frontend/**'
  pull_request:
    paths:
      - 'BitAndBeam/frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BitAndBeam/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run lint & format checks
        run: |
          npm run lint
          npm run format

      - name: Fail if linting issues are detected
        run: |
          npm run lint || exit 1
          npm run format || exit 1